language: node_js
node_js:
  - "8"
  - "9"
  - "10"
git:
  checkout: 5
services: mongodb  
cache:  
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test
