version: '3.8'

services:
  mongo:
    image: mongo

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: publicphone
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - POSTGRES_URI=postgresql://admin:admin@postgres:5432/publicphone
    links:
      - mongo
      - postgres
    depends_on:
      - mongo
      - postgres

volumes:
  postgres-data:
