version: '3'
services:
  mongo:
    image: mongo:3.6
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
    depends_on:
      - mongo  
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     